//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT3_PhamThanhDat_2210900007_Pj2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHoaDon
    {
        public int Id { get; set; }
        public Nullable<int> HoaDonID { get; set; }
        public Nullable<int> SanPhamID { get; set; }
        public Nullable<int> SoLuongMua { get; set; }
        public Nullable<double> DonGiaMua { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public Nullable<byte> TrangThai { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
