//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT3_PhamThanhDat_2210900007_Pj2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuanTri
    {
        public int Id { get; set; }
        public string TaiKhoan { get; set; }
        public Nullable<byte> TrangThai { get; set; }
    }
}
